name: demo-action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run a sample
        run: echo hello world
      - name: Build project
        run: |
          # Add your build commands here
          echo "Building project..."
          mkdir -p build
          echo "Sample artifact" > build/artifact.txt
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
